ITEP-70236 Auto formatted markdown, json, yml, html, js, gltf files with prettier tool (#119)
## 📝 Description

Ran `make prettier-write` command against current code. Those changes
shouldn't affect functionality.

Some files were reported to have invalid syntax, fixed that manually.

List of syntax errors and manual fixes:

* [error] controller/docs/user-guide/api-docs/scene-controller-api.yaml:
SyntaxError: Map keys must be unique; "timestamp" is repeated (35:13)
* [error] percebro/docs/user-guide/api-docs/percebro-api.yaml:
SyntaxError: Map keys must be unique; "timestamp" is repeated (40:13)
  * Removed one key
* [error] manager/src/templates/scene/scene_detail.html: SyntaxError:
Unexpected closing tag "div". It may happen when the tag has already
been closed by another tag. For more info see
https://www.w3.org/TR/html5/syntax.html#closing-elements-that-have-implied-end-tags
(77:1)
  * Removed 3 </div> tags
* [error] controller/tools/tracker/standard-tests.json: SyntaxError: The
input should contain exactly one expression, but the first expression is
followed by the unexpected character `{`. (2:1)
  * Added `,` between items and enclosed everything in []
* [error] manager/src/templates/asset/asset_list.html: SyntaxError:
Opening tag "a" not terminated. (10:1)
* [error] manager/src/templates/cam/cam_list.html: SyntaxError: Opening
tag "a" not terminated. (10:1)
* [error]
manager/src/templates/singleton_sensor/singleton_sensor_list.html:
SyntaxError: Opening tag "a" not terminated. (10:1)
* [error] manager/src/templates/sscape/base_3d.html: SyntaxError:
Opening tag "a" not terminated. (52:13)
* [error] manager/src/templates/sscape/base.html: SyntaxError: Opening
tag "a" not terminated. (52:13)
  * Replaced inside " with '
* [error] manager/src/templates/cam/cam_list.html: SyntaxError:
Unexpected closing tag "div". It may happen when the tag has already
been closed by another tag. For more info see
https://www.w3.org/TR/html5/syntax.html#closing-elements-that-have-implied-end-tags
(49:1)
  * Removed unused div closure

## ✨ Type of Change

Select the type of change your PR introduces:

- [ ] 🐞 **Bug fix** – Non-breaking change which fixes an issue
- [ ] 🚀 **New feature** – Non-breaking change which adds functionality
- [x] 🔨 **Refactor** – Non-breaking change which refactors the code base
- [ ] 💥 **Breaking change** – Changes that break existing functionality
- [ ] 📚 **Documentation update**
- [ ] 🔒 **Security update**
- [ ] 🧪 **Tests**
- [ ] 🚂 **CI**

## 🧪 Testing Scenarios

Describe how the changes were tested and how reviewers can test them
too:

- [ ] ✅ Tested manually
- [x] 🤖 Ran automated end-to-end tests


## ✅ Checklist

Before submitting the PR, ensure the following:

- [x] 🔍 PR title is clear and descriptive
- [ ] 📝 For internal contributors: If applicable, include the JIRA
ticket number (e.g., ITEP-123456) in the PR **title**. Do **not**
include full URLs
- [ ] 💬 I have commented my code, especially in hard-to-understand areas
- [ ] 📄 I have made corresponding changes to the documentation
- [ ] ✅ I have added tests that prove my fix is effective or my feature
works

---------

Co-authored-by: Lukasz Talarczyk <lukasz.talarczyk@intel.com>